# Generated by Django 5.1.1 on 2024-09-04 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('heartRate', models.IntegerField()),
                ('experience', models.CharField(max_length=20)),
                ('goalDistance', models.IntegerField()),
                ('distanceCovered', models.IntegerField()),
                ('result', models.TextField()),
                ('requestDateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
